/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Chart: typeof import('./src/components/DltChart.vue')['default']
    DltChart: typeof import('./src/components/DltChart.vue')['default']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElRow: typeof import('element-plus/es')['ElRow']
    SsqChart: typeof import('./src/components/SsqChart.vue')['default']
  }
}
